# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ee0827e7edb5c983cf6b2a5d9ba15b7e41c2d17830b1b65beecabacd7d95c527fe1e6b079a13a9e941550eb612f147e80b3b8cc175f07222af3ef93ed4643f

test:
  secret_key_base: 844cc54df68cda5d6994585051b9c14a3253664fb158bae33130394fec01cb242028e0453ffc6b04309d727dd2ae8a1354722fb2a5dcd9ecd4d6a6900fcf6987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
